name: Development
on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@main

      - name: Login to Azure Container Registry
        uses: azure/docker-login@master
        with:
          login-server: ${{ vars.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push image to ACR
        run: |
          docker build -t ${{ vars.REGISTRY_NAME }}.azurecr.io/zt-pii-agent:dev-${{ github.sha }} -f .docker/Dockerfile .
          docker push ${{ vars.REGISTRY_NAME }}.azurecr.io/zt-pii-agent:dev-${{ github.sha }}